### ISSUE TITLE
Add Individual Cases component

### ISSUE THREAD

**Issue by baddlan** [DigitalState/Portal#15]
"My Cases" component a.k.a. the cases that the individual are the “Identity” of that case.

**Comment by StephenOTT** [comment]
- [x] Add Case Gov ID to Cases list view
- [x] Add Case State (Open/Closed) to Cases list view
- [x] Add Case Created Date to Cases list view - Based on a property in the `Data` field.
- [x] Sort Cases in Cases List view in Reverse Order

**Comment by StephenOTT** [comment]
see the following for example of what Case View will contain for fields.  DO NOT copy this.  This is purely for vision example.

![untitled](https://user-images.githubusercontent.com/1994838/28998433-dfa9ad22-79f8-11e7-8694-1fec19f4b1d9.png)
