### ISSUE TITLE
Formio forms are not rendering Form Column Layouts correctly (Safari)

### ISSUE THREAD

**Issue by StephenOTT** [DigitalState/Portal#17]
![screen shot 2017-08-05 at 5 22 24 pm](https://user-images.githubusercontent.com/1994838/28998841-bd794ba4-7a02-11e7-92b9-9cb51fd0a5ce.png)
![screen shot 2017-08-05 at 5 22 31 pm](https://user-images.githubusercontent.com/1994838/28998842-be73735e-7a02-11e7-9d14-b74cef01cd17.png)

Notice the first two fields.  The editor has them in two columns, but the renderer in Portal and Admin are stacking the forms.

Problem occurs on Safari

**Comment by baddlan** [comment]
Fixed!
