### ISSUE TITLE
Remove Response Modal Popup on Succesfull submission of BPM Services (Formio forms)

### ISSUE THREAD

**Issue by StephenOTT** [DigitalState/Portal#18]
Remove the modal popup.  Should only be shown on the Admin UI.

![screen shot 2017-08-05 at 6 18 43 pm](https://user-images.githubusercontent.com/1994838/28999158-a64da99a-7a0a-11e7-945c-5a1e7ea914f8.png)

**Comment by baddlan** [comment]
Fixed!
