### ISSUE TITLE
enabling a disabled save button on Profile page provides a "sample" success message

### ISSUE THREAD

**Issue by StephenOTT** [DigitalState/Portal#21]
![screen shot 2017-08-05 at 6 40 18 pm](https://user-images.githubusercontent.com/1994838/28999249-a44fbd60-7a0d-11e7-902d-8c2e17cb9db7.png)

If you enable the save button on the profile page (by editing the html in the browser) and then select save the above occurs.

**Comment by baddlan** [comment]
That was just a placeholder. It's gone now.
