### ISSUE TITLE
Implement URL redirect Post-Login when Login is required

### ISSUE THREAD

**Issue by StephenOTT** [DigitalState/Portal#24]
If i am logged out and i go to: http://SERVER:8000/#/pages/services/2eb0cfc7-0402-4bc6-8733-c00084deb15c/scenarios/e049f2b4-b249-48c2-850c-64d4c4b39527/activate

It will redirect me to login.  Once i login i am brought to Dashboard. 

It should be redirecting me to the link that i used to access the site.

**Comment by baddlan** [comment]
Fixed

**Comment by StephenOTT** [comment]
@baddlan was this implemented in Admin as well?

**Comment by baddlan** [comment]
Yes
