### ISSUE TITLE
Render dates in natural language (relative date/time)

### ISSUE THREAD

**Issue by baddlan** [DigitalState/Portal#25]
For example: `25 minutes ago. 1 hour ago. 1 day ago` and `1 week ago`.
When you hover over the relative date, it should have the full date time as a tooltip.

**Comment by StephenOTT** [comment]
![screen shot 2017-08-21 at 8 18 46 pm](https://user-images.githubusercontent.com/1994838/29543294-1726ad6a-86ae-11e7-933a-e40deda26cf7.png)
