### ISSUE TITLE
Add Service Scenario Tab selection in URL

### ISSUE THREAD

**Issue by StephenOTT** [DigitalState/Portal#48]
When a specific Tab is selected for a service scenario, the URL should reflect which tab is currently selected so a user can send that url to others.

I think preference here is using anchors ? `/.../...#xyz` ?

**Comment by baddlan** [comment]
URL pattern to open a specific scenario tab:

`http://45.79.141.45:8000/#/pages/services/{{SERVICE_UUID}}/show/scenarios/{{SCENARIO_UUID}}`

**Comment by StephenOTT** [comment]
@baddlan  When selecting a tab, does the URL update in the browser with this url pattern?
