### ISSUE TITLE
Services List does not show more than 10 items

### ISSUE THREAD

**Issue by StephenOTT** [DigitalState/Portal#52]
![screen shot 2017-09-09 at 1 56 15 pm](https://user-images.githubusercontent.com/1994838/30242572-b81552c8-9566-11e7-8df2-8a767df5e300.png)

There are 13 services.

Only 10 services are being shown, and you cannot page or scroll further.

Please add endless scrolling, and please check all portal lists for same functions.

**Comment by StephenOTT** [comment]
@baddlan are you blocked on this issue?

**Comment by baddlan** [comment]
We don't have endless scrolling yet, but I have already increased the limit to 1000.

**Comment by baddlan** [comment]
Unlimited scrolling has been implemented.
