### ISSUE TITLE
Services List calls /services and Scenarios calls /scenarios twice?

### ISSUE THREAD

**Issue by StephenOTT** [DigitalState/Portal#60]
![screen shot 2017-09-27 at 7 59 07 pm](https://user-images.githubusercontent.com/1994838/30943384-af482c7c-a3be-11e7-847c-fd290d18ab79.png)

Why does Services get called twice on the Get Services List page?
`/#/pages/services/list`

**Comment by StephenOTT** [comment]
Same goes with Scenarios

**Comment by baddlan** [comment]
Those calls are made by Restangular to fetch headers first using OPTIONS and then perform a GET.
