### ISSUE TITLE
Task lisk link to single Task should be to Activate

### ISSUE THREAD

**Issue by StephenOTT** [DigitalState/Portal#61]
Lets make the main click of a task on the task list do a activation. and lets add a circle with `i` icon that appears when hovering over the specific task, and when you clikc that icon it takes you to the view page. 

Maybe top right cover of task?

@baddlan ideas?

**Comment by baddlan** [comment]
Added (info) icon below the title since users cannot hover over links in mobile devices.
The main task link does the activation.
