### ISSUE TITLE
Services: Description and presentation fields are not respecting new line characters

### ISSUE THREAD

**Issue by StephenOTT** [DigitalState/Portal#64]
Admin:
![screen shot 2017-10-04 at 4 46 52 pm](https://user-images.githubusercontent.com/1994838/31255499-29d2b52e-a9fb-11e7-943c-6032e7bbaa4c.png)

Portal:
![screen shot 2017-10-04 at 4 46 22 pm](https://user-images.githubusercontent.com/1994838/31255509-3072bbb8-a9fb-11e7-8939-9f0790e1a354.png)

@mario-digitalstate @baddlan should be accept HTML in the description and presentation fields?

**Comment by StephenOTT** [comment]
@baddlan what was the implemented fix?

**Comment by baddlan** [comment]
This is implemented only for the Description fields and not Presentation fields since they are not textareas.
