### ISSUE TITLE
Service Directory list should use the Service Description field not the Presentation field

### ISSUE THREAD

**Issue by StephenOTT** [DigitalState/Portal#81]
Service Directory list should use the Service Description field not the Presentation field

![screen shot 2017-11-30 at 12 30 19 pm](https://user-images.githubusercontent.com/1994838/33445382-b5d6d4ec-d5ca-11e7-8861-6eb46a6a8f9b.png)

**Comment by StephenOTT** [comment]
Also the Admin Page needs to be updated to swap the description and presentation fields.

Description should be single line and Presentation is multi-line

**Comment by baddlan** [comment]
Done
